name: "yig"
services:
  bot:
    build: .
    restart: always
    depends_on:
      database:
        condition: service_started
    env_file:
      - .env
  database:
    image: postgres
    restart: always
    expose:
      - "5432"
    ports:
      - "127.0.0.1:5432:5432"
    env_file:
      - .env
    volumes:
      - db:/home/data

volumes:
  db: